version: "3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=blogdatabase
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails-app
    ports:
      - "3000:3000"
    depends_on:
      - db
